# Generated by Django 6.0.4 on 2026-06-10 09:09

import usermanagement_24782037.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_24782037', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', usermanagement_24782037.models.CustomUserManager()),
            ],
        ),
    ]
