# Generated by Django 6.0.3 on 2026-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_report_reporter_name_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter_name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
