# Generated by Django 6.0.4 on 2026-05-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_24782037', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
